### ISSUE TITLE
为什么按例子测试出错： “ NoMethodError: undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>”

### ISSUE THREAD

**Issue by gogo52cn** [yeezon/yhsd-api-ruby#1]
params = {
    "redirect": {
      "path": "/12345",
      "target": "/blogs"
    }
  }
  code, body, header = YhsdApi::PrivateApp.put("redirects", params)

出错： NoMethodError: undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>

**Comment by gogo52cn** [comment]
Stack Trace:

```
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:278:in `block in stringify_headers'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/rest-client-1.6.7/lib/restclient.rb:80:in `put'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/yhsd_api-0.0.3/lib/yhsd_api/http.rb:72:in `put'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/yhsd_api-0.0.3/lib/yhsd_api/private_app.rb:96:in `put'
from (irb):37
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
from /Users/mango/Documents/glasstic/bin/rails:9:in `<top (required)>'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
from /Users/mango/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
from /Users/mango/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Users/mango/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from -e:1:in `<main>'2.2.1 :038 > 
```
